# This is the minimal config file for an NNI experiment.
# Use "nnictl create --config config.yml" to launch this experiment.
# Afterwards, you can check "config_detailed.yml" for more explanation.

experimentName: autoMGN-RL-with-meshsize
searchSpaceFile: search_space.json
trialCommand: python3 autoMGN.py  # NOTE: change "python3" to "python" if you are using Windows
trialGpuNumber: 1
trialConcurrency: 1
maxExperimentDuration: 3h
maxTrialNumber: 4
tuner:
  name: GridSearch
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: True
